name: starry_tools
description: "A Galgame Json Editor."
publish_to: 'none'

version: 0.0.1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  riverpod_annotation: ^2.6.1
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0
  getwidget: ^6.0.0
  animations: ^2.0.11
  flutter_svg: ^2.2.0
  go_router: ^15.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  riverpod_generator: ^2.6.5
  build_runner: ^2.5.2

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
  fonts:
   - family: ResourceHanRoundedCN
     fonts:
       - asset: assets/fonts/ResourceHanRoundedCN-Regular.ttf
         weight: 300
       - asset: assets/fonts/ResourceHanRoundedCN-Bold.ttf
         weight: 700
       - asset: assets/fonts/ResourceHanRoundedCN-Medium.ttf
         weight: 500
       - asset: assets/fonts/ResourceHanRoundedCN-Normal.ttf
         weight: 400
   - family: ResourceHanRoundedJP
     fonts:
       - asset: assets/fonts/ResourceHanRoundedJP-Regular.ttf
         weight: 300
       - asset: assets/fonts/ResourceHanRoundedJP-Bold.ttf
         weight: 700
       - asset: assets/fonts/ResourceHanRoundedJP-Medium.ttf
         weight: 500
       - asset: assets/fonts/ResourceHanRoundedJP-Normal.ttf
         weight: 400

